#!/bin/bash

# Auto-generated script to process 32 incomplete videos

#python individual_video_processor.py --camera_path "/nas/project_data/B1_Behavior/rush/kaan/hoi/processed_data/orginal_frames/zolti_session1_19/cam_side_r" --output_dir "/nas/project_data/B1_Behavior/rush/kaan/hoi/processed_data/hand_detections" --gpu_id 0
#python individual_video_processor.py --camera_path "/nas/project_data/B1_Behavior/rush/kaan/hoi/processed_data/orginal_frames/zolti_session2_23/cam_top" --output_dir "/nas/project_data/B1_Behavior/rush/kaan/hoi/processed_data/hand_detections" --gpu_id 0
#python individual_video_processor.py --camera_path "/nas/project_data/B1_Behavior/rush/kaan/hoi/processed_data/torso_hands_removed/imi_session1_2/cam_side_l" --output_dir "/nas/project_data/B1_Behavior/rush/kaan/hoi/processed_data/hand_detections" --gpu_id 0
#python individual_video_processor.py --camera_path "/nas/project_data/B1_Behavior/rush/kaan/hoi/processed_data/torso_hands_removed/imi_session1_3/cam_side_l" --output_dir "/nas/project_data/B1_Behavior/rush/kaan/hoi/processed_data/hand_detections" --gpu_id 0
#python individual_video_processor.py --camera_path "/nas/project_data/B1_Behavior/rush/kaan/hoi/processed_data/torso_hands_removed/imi_session1_4/cam_side_l" --output_dir "/nas/project_data/B1_Behavior/rush/kaan/hoi/processed_data/hand_detections" --gpu_id 0
#python individual_video_processor.py --camera_path "/nas/project_data/B1_Behavior/rush/kaan/hoi/processed_data/torso_hands_removed/imi_session1_5/cam_side_l" --output_dir "/nas/project_data/B1_Behavior/rush/kaan/hoi/processed_data/hand_detections" --gpu_id 0
#python individual_video_processor.py --camera_path "/nas/project_data/B1_Behavior/rush/kaan/hoi/processed_data/torso_hands_removed/imi_session1_6/cam_side_l" --output_dir "/nas/project_data/B1_Behavior/rush/kaan/hoi/processed_data/hand_detections" --gpu_id 0
#python individual_video_processor.py --camera_path "/nas/project_data/B1_Behavior/rush/kaan/hoi/processed_data/torso_hands_removed/imi_session1_7/cam_side_l" --output_dir "/nas/project_data/B1_Behavior/rush/kaan/hoi/processed_data/hand_detections" --gpu_id 0
#python individual_video_processor.py --camera_path "/nas/project_data/B1_Behavior/rush/kaan/hoi/processed_data/torso_hands_removed/imi_session1_8/cam_side_l" --output_dir "/nas/project_data/B1_Behavior/rush/kaan/hoi/processed_data/hand_detections" --gpu_id 0
#python individual_video_processor.py --camera_path "/nas/project_data/B1_Behavior/rush/kaan/hoi/processed_data/torso_hands_removed/imi_session1_9/cam_side_l" --output_dir "/nas/project_data/B1_Behavior/rush/kaan/hoi/processed_data/hand_detections" --gpu_id 0
#python individual_video_processor.py --camera_path "/nas/project_data/B1_Behavior/rush/kaan/hoi/processed_data/torso_hands_removed/imi_session2_10/cam_side_l" --output_dir "/nas/project_data/B1_Behavior/rush/kaan/hoi/processed_data/hand_detections" --gpu_id 0
# python individual_video_processor.py --camera_path "/nas/project_data/B1_Behavior/rush/kaan/hoi/processed_data/torso_hands_removed/imi_session2_11/cam_side_l" --output_dir "/nas/project_data/B1_Behavior/rush/kaan/hoi/processed_data/hand_detections" --gpu_id 0
# python individual_video_processor.py --camera_path "/nas/project_data/B1_Behavior/rush/kaan/hoi/processed_data/torso_hands_removed/imi_session2_12/cam_side_l" --output_dir "/nas/project_data/B1_Behavior/rush/kaan/hoi/processed_data/hand_detections" --gpu_id 0
# python individual_video_processor.py --camera_path "/nas/project_data/B1_Behavior/rush/kaan/hoi/processed_data/torso_hands_removed/imi_session2_13/cam_side_l" --output_dir "/nas/project_data/B1_Behavior/rush/kaan/hoi/processed_data/hand_detections" --gpu_id 0
# python individual_video_processor.py --camera_path "/nas/project_data/B1_Behavior/rush/kaan/hoi/processed_data/torso_hands_removed/imi_session2_14/cam_side_l" --output_dir "/nas/project_data/B1_Behavior/rush/kaan/hoi/processed_data/hand_detections" --gpu_id 0
# python individual_video_processor.py --camera_path "/nas/project_data/B1_Behavior/rush/kaan/hoi/processed_data/torso_hands_removed/imi_session2_15/cam_side_l" --output_dir "/nas/project_data/B1_Behavior/rush/kaan/hoi/processed_data/hand_detections" --gpu_id 0
# python individual_video_processor.py --camera_path "/nas/project_data/B1_Behavior/rush/kaan/hoi/processed_data/torso_hands_removed/zolti_session1_16/cam_side_l" --output_dir "/nas/project_data/B1_Behavior/rush/kaan/hoi/processed_data/hand_detections" --gpu_id 0
# python individual_video_processor.py --camera_path "/nas/project_data/B1_Behavior/rush/kaan/hoi/processed_data/torso_hands_removed/zolti_session1_17/cam_side_l" --output_dir "/nas/project_data/B1_Behavior/rush/kaan/hoi/processed_data/hand_detections" --gpu_id 0
# python individual_video_processor.py --camera_path "/nas/project_data/B1_Behavior/rush/kaan/hoi/processed_data/torso_hands_removed/zolti_session1_18/cam_side_l" --output_dir "/nas/project_data/B1_Behavior/rush/kaan/hoi/processed_data/hand_detections" --gpu_id 0
# python individual_video_processor.py --camera_path "/nas/project_data/B1_Behavior/rush/kaan/hoi/processed_data/orginal_frames/zolti_session1_19/cam_top" --output_dir "/nas/project_data/B1_Behavior/rush/kaan/hoi/processed_data/hand_detections" --gpu_id 0
#python individual_video_processor.py --camera_path "/nas/project_data/B1_Behavior/rush/kaan/hoi/processed_data/torso_hands_removed/zolti_session1_19/cam_side_l" --output_dir "/nas/project_data/B1_Behavior/rush/kaan/hoi/processed_data/hand_detections" --gpu_id 1
python individual_video_processor.py --camera_path "/nas/project_data/B1_Behavior/rush/kaan/hoi/processed_data/torso_hands_removed/zolti_session1_20/cam_side_l" --output_dir "/nas/project_data/B1_Behavior/rush/kaan/hoi/processed_data/hand_detections" --gpu_id 1
python individual_video_processor.py --camera_path "/nas/project_data/B1_Behavior/rush/kaan/hoi/processed_data/torso_hands_removed/zolti_session2_21/cam_side_l" --output_dir "/nas/project_data/B1_Behavior/rush/kaan/hoi/processed_data/hand_detections" --gpu_id 1
python individual_video_processor.py --camera_path "/nas/project_data/B1_Behavior/rush/kaan/hoi/processed_data/torso_hands_removed/zolti_session2_22/cam_side_l" --output_dir "/nas/project_data/B1_Behavior/rush/kaan/hoi/processed_data/hand_detections" --gpu_id 1
python individual_video_processor.py --camera_path "/nas/project_data/B1_Behavior/rush/kaan/hoi/processed_data/orginal_frames/zolti_session2_23/cam_side_r" --output_dir "/nas/project_data/B1_Behavior/rush/kaan/hoi/processed_data/hand_detections" --gpu_id 1
python individual_video_processor.py --camera_path "/nas/project_data/B1_Behavior/rush/kaan/hoi/processed_data/torso_hands_removed/zolti_session2_23/cam_side_l" --output_dir "/nas/project_data/B1_Behavior/rush/kaan/hoi/processed_data/hand_detections" --gpu_id 1
python individual_video_processor.py --camera_path "/nas/project_data/B1_Behavior/rush/kaan/hoi/processed_data/orginal_frames/zolti_session2_24/cam_side_r" --output_dir "/nas/project_data/B1_Behavior/rush/kaan/hoi/processed_data/hand_detections" --gpu_id 1
python individual_video_processor.py --camera_path "/nas/project_data/B1_Behavior/rush/kaan/hoi/processed_data/orginal_frames/zolti_session2_24/cam_top" --output_dir "/nas/project_data/B1_Behavior/rush/kaan/hoi/processed_data/hand_detections" --gpu_id 1
python individual_video_processor.py --camera_path "/nas/project_data/B1_Behavior/rush/kaan/hoi/processed_data/torso_hands_removed/zolti_session2_24/cam_side_l" --output_dir "/nas/project_data/B1_Behavior/rush/kaan/hoi/processed_data/hand_detections" --gpu_id 1
python individual_video_processor.py --camera_path "/nas/project_data/B1_Behavior/rush/kaan/hoi/processed_data/orginal_frames/zolti_session2_25/cam_side_r" --output_dir "/nas/project_data/B1_Behavior/rush/kaan/hoi/processed_data/hand_detections" --gpu_id 1
python individual_video_processor.py --camera_path "/nas/project_data/B1_Behavior/rush/kaan/hoi/processed_data/orginal_frames/zolti_session2_25/cam_top" --output_dir "/nas/project_data/B1_Behavior/rush/kaan/hoi/processed_data/hand_detections" --gpu_id 1
python individual_video_processor.py --camera_path "/nas/project_data/B1_Behavior/rush/kaan/hoi/processed_data/torso_hands_removed/zolti_session2_25/cam_side_l" --output_dir "/nas/project_data/B1_Behavior/rush/kaan/hoi/processed_data/hand_detections" --gpu_id 1
